name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  success:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Lab 7 CI/CD Test
      run: |
        echo "✅ CI/CD Pipeline is working!"
        echo "Lab 7 completed successfully!"
        echo "Project files:"
        dir
